---
title: "Ryan Hunter"
---

Hello, Website!

For more information about simple R Markdown websites, please read the documentation at https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html.

Please also note that simple R Markdown sites are _not_ based on **blogdown**. They are probably good for websites with only a few Rmd documents. For larger-scale and more sophisticated websites (such as blogs), you may want to use **blogdown** instead: https://github.com/rstudio/blogdown.

# Welcome to My Portfolio

**Hi, I’m Ryan Hunter!**  

 I am student that is passionate about the numbers within a business and giving solutions to businesses that may help them achieve their goals. I have acquired several skills through my MGMT 230 class such as: R Studio language, web development through HTML, and data analysis. 
---

## Skills & Focus Areas

- Web Development: HTML, JavaScript  
- Data Analysis: R, Python. 
- Other Skills: Git, GitHub.

---

## Navigation

- [About Me](about.html)
- [Projects](projects.html)
